name: Build AMMF2 Module

on:
  push:
    branches: [main]
  workflow_dispatch: # 允许手动触发

jobs:
  run-ammf2-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          path: "./overlay"

      - name: Clone AMMF2 repository
        run: |
          git clone --depth=1 https://github.com/Aurora-Nasa-1/AMMF2.git ammf2
          cd ammf2
          rm -rf .git

      - name: Copy files
        run: |
          cd ./overlay
          find . -type f -not -path "./ammf2/*" | while read -r file; do
           # 去除路径开头的./
           relative_path=${file#./}

              # 检查文件是否存在于ammf2目录中
           if [ ! -f "../ammf2/$relative_path" ]; then
              # 创建目标目录（如果不存在）
              target_dir="../ammf2/$(dirname "$relative_path")"
              mkdir -p "$target_dir"

             # 复制文件
             cp "$file" "../ammf2/$relative_path"
             echo "已复制: $relative_path"
           fi
          done
          cp ./customize.sh ../ammf2/files/scripts/install_custom_script.sh
          cp ./service.sh ../ammf2/files/scripts/service_script.sh

      - name: Get current time
        run: |
          cd ./ammf2
          random_number=$((RANDOM % 100))
          echo "$random_number" > current_time.txt

      - name: Get latest tag
        run: |
          cd ./overlay
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "$LATEST_TAG" > ../ammf2/latest_tag.txt

      - name: Make module.prop
        run: |
          cd ./ammf2
          LATEST_TAG=$(cat latest_tag.txt)
          CURRENT_TIME=$(cat current_time.txt)
          . ./module_settings/config.sh
          echo "id=${action_id}" > module.prop
          echo "name=${action_name}" >> module.prop
          echo "version=${LATEST_TAG}" >> module.prop
          echo "versionCode=${CURRENT_TIME}" >> module.prop
          echo "author=${action_author}" >> module.prop
          echo "description=${action_description}" >> module.prop
          echo "updateJson=${updateJson}" >> module.prop
          cat module.prop
          mkdir -p bin

      - name: Replace module ID in files
        run: |
          cd ./ammf2
          LATEST_TAG=$(cat latest_tag.txt)
          . ./module_settings/config.sh
          # 替换文件中的模块ID
          find webroot -name "*.js" -exec sed -i "s/v114514/${LATEST_TAG}/g" {} \;
          find webroot -name "status.js" -exec sed -i "s/Aurora-Nasa-1\/AMMF/${Github_update_repo}/g" {} \;
          find files -name "*.sh" -exec sed -i "s/AMMF/${action_id}/g" {} \;
          find webroot -name "*.js" -exec sed -i "s/AMMF/${action_id}/g" {} \;
          find src -name "*.cpp" -exec sed -i "s/AMMF2/${action_id}/g" {} \;
          sed -i "s/AMMF/${action_id}/g" webroot/index.html
          echo "已完成模块ID替换"

      - name: Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26d
          
      - name: Find and build all C++ files
        run: |
          cd ./ammf2
          . module_settings/config.sh
          export CFLAGS="-O3 -flto"
          export CXXFLAGS="-O3 -flto -std=c++20"
          # 查找所有cpp文件并构建
          for cpp_file in src/*.cpp; do
            filename=$(basename -- "$cpp_file" .cpp)
            
            # 构建aarch64版本
            $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++ \
              $CXXFLAGS -Wall -Wextra -static-libstdc++ \
              -I src -I src/ \
              -o "bin/${filename}-${action_id}-aarch64" "$cpp_file"
            
            # 构建x86_64版本
            $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android21-clang++ \
              $CXXFLAGS -Wall -Wextra -static-libstdc++ \
              -I src -I src/ \
              -o "bin/${filename}-${action_id}-x86_64" "$cpp_file"
          done

      - name: Strip binaries
        run: |
          cd ./ammf2
          # 自动strip所有生成的二进制文件
          for binary in bin/*-aarch64 bin/*-x86_64; do
            $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip "$binary" || echo "Failed to strip $binary"
          done
          
      - name: Remove files
        run: |
          cd ./ammf2
          rm -rf src
          rm build.sh
          rm latest_tag.txt
          rm current_time.txt
          
      - name: Create META-INF directory structure
        run: |
          cd ./ammf2
          mkdir -p META-INF/com/google/android
          echo '#MAGISK' > META-INF/com/google/android/updater-script

      - name: Upload zip files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}_${{ env.SHORT_SHA }}
          path: ammf2/*